### ISSUE TITLE
post_max_size substitution error

### ISSUE THREAD

**Issue by jeff-kilbride** [matriphe/docker-alpine-php#1]
I copied some of your `sed` statements to my own `Dockerfile` and noticed the following error:

```
sed -i "s|post_max_size =.*|max_file_uploads = ${PHP_MAX_POST}|" /etc/php/php.ini && \
```

You are replacing the `post_max_size` config with `max_file_uploads`. Just a heads up...

**Comment by matriphe** [comment]
Thanks for your notice! 👍
