### ISSUE TITLE
date.timezone sed isn't replacing

### ISSUE THREAD

**Issue by bazaglia** [matriphe/docker-alpine-php#2]
Hello,

Nice Dockerfile. I've experienced an issue in this line though:

`sed -i "s|;date.timezone =.*|date.timezone = ${TIMEZONE}|" /etc/php/php.ini`

Timezone isn't replaced with the env in php.ini, keeping the original line `date.timezone = UTC` in `php.ini`. Any idea?

**Comment by matriphe** [comment]
Thanks for the issue, I will check it.

**Comment by bazaglia** [comment]
@matriphe In this expression you're considering a `;` before `date.timezone`. However, it looks like there's no `;` for commenting this line in default php.ini. Removing the `;` in sed worked for me. The ideal may be considering both cases in php.ini (with and without a `;` in the start of the line). I would love to help you with this and submit a PR but I'm not good in sed.

**Comment by matriphe** [comment]
@bazaglia in some PHP.ini config, the `date.timeszone` is commented using `;` 

thanks for your comment.

**Comment by matriphe** [comment]
@bazaglia if you want to make a PR, please do.. I'm not good in seed either.. :D
