### ISSUE TITLE
Connect() failed (111: Connection refused)

### ISSUE THREAD

**Issue by macmladen** [matriphe/docker-alpine-php#5]
The issue opened in matriphe/docker-alpine-nginx#1 actually belongs here because it is a a change in PHP (tag: fpm7) configuration that prevents connection.

The reason why connection is refused is because it only can listen on 127.0.0.1:9000, and that can be checked in `/etc/php7/php-fpm.d/www.conf` line 36.

This fix matriphe/docker-alpine-php#4 solves that by fixing proper file.

**Comment by matriphe** [comment]
Thanks!
